# Generated by Django 4.2 on 2023-04-25 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='title',
            new_name='ingredient_name',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='units',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='title',
            new_name='recipe',
        ),
        migrations.RemoveField(
            model_name='reciperequirement',
            name='require',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='menu_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitems', to='inventory.menuitem'),
        ),
        migrations.RemoveField(
            model_name='reciperequirement',
            name='ingredient',
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitem', to='inventory.menuitem'),
        ),
        migrations.AddField(
            model_name='reciperequirement',
            name='ingredient',
            field=models.ManyToManyField(to='inventory.ingredient'),
        ),
    ]
