# Generated by Django 4.2 on 2023-04-30 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_title_ingredient_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciperequirement', to='inventory.reciperequirement'),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='menu_item',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
