# Generated by Django 4.2 on 2023-04-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_recipe_menuitem_menu_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='client',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='menu_items',
        ),
        migrations.RemoveField(
            model_name='reciperequirement',
            name='recipe',
        ),
        migrations.AddField(
            model_name='reciperequirement',
            name='menu_item',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
